// <auto-generated />
using EmpEx1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmpEx1.Migrations
{
    [DbContext(typeof(DemoContext))]
    partial class DemoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmpEx1.Models.Emp", b =>
                {
                    b.Property<long>("EmpID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EmpID"));

                    b.Property<string>("EmpName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpID");

                    b.ToTable("Emps");
                });

            modelBuilder.Entity("EmpEx1.Models.EmpEducation", b =>
                {
                    b.Property<long>("EmpEducationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EmpEducationID"));

                    b.Property<string>("CollegeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("EmpID")
                        .HasColumnType("bigint");

                    b.Property<string>("Field")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ObtainMarks")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalMarks")
                        .HasColumnType("bigint");

                    b.Property<string>("standard")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpEducationID");

                    b.HasIndex("EmpID");

                    b.ToTable("EmpEducations");
                });

            modelBuilder.Entity("EmpEx1.Models.EmpEducation", b =>
                {
                    b.HasOne("EmpEx1.Models.Emp", "Emp")
                        .WithMany("EmpEducations")
                        .HasForeignKey("EmpID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emp");
                });

            modelBuilder.Entity("EmpEx1.Models.Emp", b =>
                {
                    b.Navigation("EmpEducations");
                });
#pragma warning restore 612, 618
        }
    }
}
